# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: 📬 Contact Luke
    url: https://github.com/lukeponga-dev
    about: Reach out for questions, feedback, or collaboration
